CREATE TABLE IF NOT EXISTS "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" character varying(200) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Usuarios_Email"
ON "Usuarios" ("Email");

CREATE TABLE IF NOT EXISTS "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" character varying(100) NOT NULL,
    "Color" character varying(20) NOT NULL,
    "Descripcion" character varying(500),
    "UsuarioEmail" character varying(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Gastos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Descripcion" character varying(200) NOT NULL,
    "Monto" numeric(18,2) NOT NULL,
    "Fecha" date NOT NULL,
    "CategoriaId" integer NOT NULL,
    "CategoriaNombre" character varying(100) NOT NULL,
    "MetodoPago" character varying(30) NOT NULL,
    "TipoMonto" character varying(20) NOT NULL,
    "Notas" character varying(500),
    "UsuarioEmail" character varying(150) NOT NULL,
    CONSTRAINT "FK_Gastos_Categorias_CategoriaId"
        FOREIGN KEY ("CategoriaId")
        REFERENCES "Categorias" ("Id")
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Gastos_CategoriaId"
ON "Gastos" ("CategoriaId");

CREATE TABLE IF NOT EXISTS "PresupuestosMensuales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Mes" integer NOT NULL,
    "Anio" integer NOT NULL,
    "Monto" numeric(18,2) NOT NULL,
    "OrigenFondos" character varying(30),
    "UsuarioEmail" character varying(150) NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_PresupuestosMensuales_UsuarioEmail_Mes_Anio"
ON "PresupuestosMensuales" ("UsuarioEmail", "Mes", "Anio");
